name: sync_wording_example
description: "The Flutter sync_wording example project."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sync_wording:
    git: git@github.com:BeTomorrow/sync-wording-dart.git

flutter:
  uses-material-design: true
  generate: true
