name: sync_wording
version: 1.1.0
description: A dart command-line application to generate localization assets and class files used by your Flutter application from a GoogleSheet document.
repository: https://github.com/BeTomorrow/sync-wording-dart
homepage: https://github.com/BeTomorrow/sync-wording-dart
issue_tracker: https://github.com/BeTomorrow/sync-wording-dart/issues

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.5.0
  yaml: ^3.1.2
  http: ^1.2.2
  googleapis_auth: ^2.0.0
  googleapis: ^14.0.0
  collection: ^1.19.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

topics:
  - localization
  - translation
  - wording
  - googlesheets

false_secrets:
 - /lib/config/wording_config_loader.dart
 - /test/config/wording_config_loader_test.dart
